
services:
  postgres:
    image: postgres:18-alpine
    container_name: upcycle_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: upcycle
    ports:
      - "5440:5432"
    volumes:
      - upcycle_db_data:/var/lib/postgresql

volumes:
  upcycle_db_data:
